[workspace]
members = [
    "for-loop",
    "guess",
    "serde_json_demo",
    "vec_demo",
    "ref_borrow_demo",
    "iterator_demo",
    "mem_demo",
    "tcpserver",
    "tcpclient",
    "the_algorithms",
    "args_parse",
]
