[package]
name = "polars-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
polars = "0.46.0"
serde = { version = "1.0", features = ["derive"] }
polars_excel_writer = "0.12.0"
